### ISSUE TITLE
Docker container /gtfs2ldes-js:20230306t2329: crashed with 2023-04-21 16:23:55 SyntaxError: Unexpected token { in JSON at position 1232

### ISSUE THREAD

**Issue by xdxxxdx** [julianrojas87/gtfs2ldes-js#14]
Hello @julianrojas87 ,

I am using your component ` /gtfs2ldes-js:20230306t2329` to test the VSDS solution. 
The full set up could be seen here: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/tests/011.server-geo-fragment-large-ldes/docker-compose.yml

```
 gtfs2ldes-js:
    container_name: ${USECASE_NAME:-gtfs-geo-fragment}_gtfs2ldes-js
    image: ghcr.io/julianrojas87/gtfs2ldes-js:${GTFS2LDES_TAG:-20230306t2329}
    environment:
      - GTFS_SOURCE=${GTFS_SOURCE:-https://www.rtd-denver.com/files/gtfs/bustang-co-us.zip}
      - GTFSRT_SOURCE=${GTFSRT_SOURCE:-https://www.rtd-denver.com/files/bustang/gtfs-rt/Bustang_TripUpdate.pb}
      - BASE_IRI=${GTFS_BASE_IRI:-http://www.rtd-denver.com/}
      - NODE_OPTIONS=${NODE_OPTIONS:-}
      - TARGET_URL=http://ldio-workflow:8080/gtfs-pipeline
      - GTFS_CRON=${GTFS_CRON:-0 0 3 1 * *}
      - GTFSRT_CRON=${GTFSRT_CRON:-*/30 * * * * *}
      - RUN_ON_LAUNCH=${RUN_ON_LAUNCH:-true}
      - THROTTLE_RATE=${THROTTLE_RATE:-100}
      - AUTH_HEADER=${AUTH_HEADER:-}
      - AUTH_HEADER_VALUE=${AUTH_HEADER_VALUE:-}
    networks:
      - ldes
    profiles:
      - delay-started
```

After a certain period, there is following crash showed inside the docker log:
`2023-04-21 16:23:55 SyntaxError: Unexpected token { in JSON at position 1232`

The full log is here: 
[gtfs2ldes_js_20230306t2329.txt](https://github.com/julianrojas87/gtfs2ldes-js/files/11296600/gtfs2ldes_js_20230306t2329.txt)

Thanks
XD
